server:
  maxThreads: 256
  minThreads: 256
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8091
  applicationContextPath: /
  requestLog:
    appenders:
      - type: console
        timeZone: IST

proxy:
  host: "walletservice.treafik.stg.phonepe.com"
  port: 80
  scheme: "http"